version: '3.8'

services:
  coinarth-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinarth-react-app
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    restart: unless-stopped
